name: Generar archivo YAML de Secret desde Vault

on:
  workflow_dispatch:

jobs:
  generar-secret-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Vault CLI
        uses: hashicorp/setup-vault@v1
        with:
          vault-version: '1.15.5'

      - name: Leer secretos desde Vault y generar archivo YAML
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}

          ORG_ID=$(vault kv get -field=SINGLESTORE_ORG_ID secret/singlestore)
          GROUP_ID=$(vault kv get -field=SINGLESTORE_WORKSPACE_GROUP_ID secret/singlestore)

          echo "apiVersion: v1" > singlestore-secret.yaml
          echo "kind: Secret" >> singlestore-secret.yaml
          echo "metadata:" >> singlestore-secret.yaml
          echo "  name: singlestore-secret" >> singlestore-secret.yaml
          echo "  namespace: singlestore-collector" >> singlestore-secret.yaml
          echo "stringData:" >> singlestore-secret.yaml
          echo "  SINGLESTORE_ORG_ID: $ORG_ID" >> singlestore-secret.yaml
          echo "  SINGLESTORE_WORKSPACE_GROUP_ID: $GROUP_ID" >> singlestore-secret.yaml

      - name: Mostrar YAML generado
        run: cat singlestore-secret.yaml
